<script setup>
import { onMounted, reactive, ref } from "vue";
import { ElMessage } from "element-plus";
import request from "../api/request";
const tab = ref("all"); const rows = ref([]); const categories = ref([]); const loading = ref(false);
const dialog = reactive({ visible: false, id: null, title: "", content: "", categoryId: null, source: "", isPublished: 0, sort: 0 });
async function load() { loading.value = true; try { categories.value = await request.get("/api/admin/article-category"); const data = tab.value === "mine" ? await request.get("/api/admin/article/mine") : await request.get("/api/admin/article/page"); rows.value = data.list; } catch (e) { ElMessage.error(e.message || "资讯加载失败"); } finally { loading.value = false; } }
function open(row = null) { Object.assign(dialog, row ? { visible: true, id: row.id, title: row.title, content: row.content, categoryId: row.categoryId, source: row.source || "", isPublished: row.isPublished, sort: row.sort || 0 } : { visible: true, id: null, title: "", content: "", categoryId: null, source: "", isPublished: 0, sort: 0 }); }
async function save() { try { await request.post("/api/admin/article", { ...dialog }); dialog.visible = false; ElMessage.success("已保存"); await load(); } catch (e) { ElMessage.error(e.message || "保存失败"); } }
async function remove(row) { try { await request.delete(`/api/admin/article/${row.id}`); ElMessage.success("已删除"); await load(); } catch (e) { ElMessage.error(e.message || "删除失败"); } }
async function addCategory() { const name = window.prompt("栏目名称"); if (!name) return; try { await request.post("/api/admin/article-category", { name }); await load(); } catch (e) { ElMessage.error(e.message || "新增栏目失败"); } }
async function removeCategory() { const id = window.prompt("要删除的栏目ID"); if (!id) return; try { await request.delete(`/api/admin/article-category/${id}`); await load(); } catch (e) { ElMessage.error(e.message || "删除栏目失败"); } }
onMounted(load);
</script>
<template><section><div class="page-heading"><h2>资讯管理</h2><div><el-button type="primary" @click="open()">发布文章</el-button><el-button @click="addCategory">新增栏目</el-button><el-button @click="removeCategory">删除栏目</el-button></div></div><el-tabs v-model="tab" @tab-change="load"><el-tab-pane label="所有文章" name="all" /><el-tab-pane label="我的发布" name="mine" /></el-tabs><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="title" label="标题" min-width="280" /><el-table-column prop="categoryName" label="栏目" width="130" /><el-table-column prop="author" label="发布人" width="120" /><el-table-column label="状态" width="100"><template #default="s">{{ s.row.isPublished === 1 ? "已发布" : "草稿" }}</template></el-table-column><el-table-column prop="viewCount" label="浏览量" width="90" /><el-table-column label="操作" width="150"><template #default="s"><el-button link type="primary" @click="open(s.row)">编辑</el-button><el-button link type="danger" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table><el-dialog v-model="dialog.visible" title="文章编辑" width="620px"><el-form label-width="80px"><el-form-item label="标题"><el-input v-model="dialog.title" /></el-form-item><el-form-item label="栏目"><el-select v-model="dialog.categoryId" clearable><el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id" /></el-select></el-form-item><el-form-item label="来源"><el-input v-model="dialog.source" /></el-form-item><el-form-item label="内容"><el-input v-model="dialog.content" type="textarea" :rows="10" /></el-form-item><el-form-item label="发布"><el-switch v-model="dialog.isPublished" :active-value="1" :inactive-value="0" /></el-form-item></el-form><template #footer><el-button @click="dialog.visible = false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></section></template>
