<script setup>
import { onMounted, ref } from "vue";
import { ElMessage } from "element-plus";
import request from "../api/request";
const flows = ref([]); const roles = ref([]); const loading = ref(false);
async function load() { loading.value = true; try { [flows.value, roles.value] = await Promise.all([request.get("/api/admin/flow"), request.get("/api/admin/role")]); } catch (error) { ElMessage.error(error.message || "流程加载失败"); } finally { loading.value = false; } }
async function save(flow) { try { await request.put(`/api/admin/flow/${flow.bizType}`, { flowName: flow.flowName, enabled: flow.enabled, nodes: flow.nodes }); ElMessage.success("流程已保存"); await load(); } catch (error) { ElMessage.error(error.message || "保存失败"); } }
async function addNode(flow) { const nodeName = window.prompt("节点名称"); if (!nodeName) return; const roleId = Number(window.prompt("审核角色ID", String(roles.value[0]?.id || ""))); if (!roleId) return; try { await request.post("/api/admin/flow-node", { flowId: flow.id, nodeName, roleId, nodeOrder: flow.nodes.length + 1 }); ElMessage.success("节点已添加"); await load(); } catch (error) { ElMessage.error(error.message || "添加失败"); } }
async function removeNode(node) { try { await request.delete(`/api/admin/flow-node/${node.id}`); ElMessage.success("节点已删除"); await load(); } catch (error) { ElMessage.error(error.message || "删除失败"); } }
onMounted(load);
</script>
<template><section><div class="page-heading"><h2>流程管理</h2><el-button :loading="loading" @click="load">刷新</el-button></div><el-alert title="修改后的流程会被后续审核任务即时读取。" type="info" :closable="false" class="flow-tip" /><el-card v-for="flow in flows" :key="flow.id" shadow="never" class="flow-card"><template #header><div class="flow-header"><span>{{ flow.flowName }}（业务类型 {{ flow.bizType }}）</span><div><el-switch v-model="flow.enabled" :active-value="1" :inactive-value="0" /><el-button type="primary" link @click="save(flow)">保存</el-button><el-button link @click="addNode(flow)">新增节点</el-button></div></div></template><el-table :data="flow.nodes" size="small"><el-table-column prop="nodeOrder" label="顺序" width="150"><template #default="scope"><el-input-number v-model="scope.row.nodeOrder" :min="1" :max="flow.nodes.length" /></template></el-table-column><el-table-column label="节点名称"><template #default="scope"><el-input v-model="scope.row.nodeName" /></template></el-table-column><el-table-column label="审核角色"><template #default="scope"><el-select v-model="scope.row.roleId"><el-option v-for="role in roles" :key="role.id" :label="role.roleName" :value="role.id" /></el-select></template></el-table-column><el-table-column label="操作" width="90"><template #default="scope"><el-button type="danger" link @click="removeNode(scope.row)">删除</el-button></template></el-table-column></el-table></el-card></section></template>
<style scoped>.flow-tip { margin-bottom: 16px; } .flow-card { margin-bottom: 16px; } .flow-header { display: flex; justify-content: space-between; align-items: center; }</style>
