<script setup>
import { onMounted, reactive, ref } from "vue";
import { ElMessage } from "element-plus";
import request from "../api/request";
const rows = ref([]); const dialog = reactive({ visible: false, id: null, code: "", title: "", contentTemplate: "", enabled: 1 });
async function load() { try { rows.value = await request.get("/api/admin/message-config"); } catch (error) { ElMessage.error(error.message || "消息配置加载失败"); } }
function edit(row) { Object.assign(dialog, { visible: true, id: row.id, code: row.code, title: row.title, contentTemplate: row.contentTemplate, enabled: row.enabled }); }
function add() { Object.assign(dialog, { visible: true, id: null, code: "", title: "", contentTemplate: "", enabled: 1 }); }
async function save() { try { const body = { code: dialog.code, title: dialog.title, contentTemplate: dialog.contentTemplate, enabled: dialog.enabled }; if (dialog.id) await request.put(`/api/admin/message-config/${dialog.id}`, body); else await request.post("/api/admin/message-config", body); dialog.visible = false; ElMessage.success("已保存"); await load(); } catch (error) { ElMessage.error(error.message || "保存失败"); } }
async function remove(row) { try { await request.delete(`/api/admin/message-config/${row.id}`); ElMessage.success("已删除"); await load(); } catch (error) { ElMessage.error(error.message || "删除失败"); } }
onMounted(load);
</script>
<template><section><div class="page-heading"><h2>消息提醒配置</h2><el-button type="primary" @click="add">新增模板</el-button></div><el-table :data="rows"><el-table-column prop="code" label="编码" width="180" /><el-table-column prop="title" label="标题" width="180" /><el-table-column prop="contentTemplate" label="内容模板" min-width="360" /><el-table-column label="状态" width="100"><template #default="scope"><el-switch v-model="scope.row.enabled" :active-value="1" :inactive-value="0" @change="edit(scope.row); save()" /></template></el-table-column><el-table-column label="操作" width="140"><template #default="scope"><el-button link @click="edit(scope.row)">编辑</el-button><el-button type="danger" link @click="remove(scope.row)">删除</el-button></template></el-table-column></el-table><el-dialog v-model="dialog.visible" title="消息模板" width="520px"><el-form label-width="100px"><el-form-item label="编码"><el-input v-model="dialog.code" /></el-form-item><el-form-item label="标题"><el-input v-model="dialog.title" /></el-form-item><el-form-item label="内容模板"><el-input v-model="dialog.contentTemplate" type="textarea" :rows="4" /></el-form-item><el-form-item label="启用"><el-switch v-model="dialog.enabled" :active-value="1" :inactive-value="0" /></el-form-item></el-form><template #footer><el-button @click="dialog.visible = false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></section></template>
