<script setup>
import { onMounted, ref } from "vue";
import { ElMessage } from "element-plus";
import request from "../api/request";
import { useOrderBadge } from "../composables/useOrderBadge";
const { fetchPendingOrderCount } = useOrderBadge();
const rows = ref([]); const loading = ref(false); const attachments = ref([]); const attachmentDialog = ref(false); const attachmentLoading = ref(false); const attachmentOrder = ref(null); const shipDialog = ref(false); const shipForm = ref({ orderId: null, orderNo: "", receiverName: "", receiverPhone: "", receiverAddress: "", company: "", trackingNo: "" }); const statusNames = ["待付款", "待审核", "待发货", "待收货", "已完成", "已取消", "退款中", "已退款"];
const portalApiBase = import.meta.env.VITE_PORTAL_API_BASE_URL || "http://localhost:8081";
async function load() { loading.value = true; try { const data = await request.get("/api/admin/order/page"); rows.value = data.list; fetchPendingOrderCount();} catch (e) { ElMessage.error(e.message || "订单加载失败"); } finally { loading.value = false; } }
async function confirm(row) { try { await request.put("/api/admin/order/confirm", { orderId: row.id }); ElMessage.success("订单已完成"); await load();fetchPendingOrderCount(); } catch (e) { ElMessage.error(e.message || "确认失败"); } }
function openShip(row) { shipForm.value = { orderId: row.id, orderNo: row.orderNo, receiverName: row.receiverName, receiverPhone: row.receiverPhone, receiverAddress: row.receiverAddress, company: "中通", trackingNo: "" }; shipDialog.value = true; }
async function submitShip() { const { orderId, company, trackingNo } = shipForm.value; if (!company || !trackingNo) return ElMessage.warning("请填写物流公司和物流单号"); try { await request.put("/api/admin/order/delivery", { orderId, company, trackingNo }); ElMessage.success("已登记发货"); shipDialog.value = false; await load(); fetchPendingOrderCount(); } catch (e) { ElMessage.error(e.message || "发货失败"); } }
async function viewAttachments(row) { attachmentOrder.value = row; attachmentDialog.value = true; attachmentLoading.value = true; try { const data = await request.get(`/api/admin/order/${row.id}/attachments`); attachments.value = (data || []).filter((item) => item.type === 1); } catch (e) { attachments.value = []; ElMessage.error(e.message || "附件加载失败"); } finally { attachmentLoading.value = false; } }
function attachmentUrl(url) { return url && /^https?:\/\//.test(url) ? url : `${portalApiBase}${url || ""}`; }
onMounted(load);
</script>
<template><section><div class="page-heading"><h2>订单管理</h2><el-button :loading="loading" @click="load">刷新</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="orderNo" label="订单号" min-width="180" /><el-table-column label="商品" min-width="220"><template #default="s">{{ s.row.details.map(d => `${d.productName} × ${d.quantity}`).join("、") }}</template></el-table-column><el-table-column prop="payAmount" label="金额" width="110" /><el-table-column label="状态" width="100"><template #default="s">{{ statusNames[s.row.orderStatus] }}</template></el-table-column><el-table-column label="收货人" width="120" prop="receiverName" /><el-table-column prop="receiverPhone" label="收货电话" min-width="130" /><el-table-column prop="receiverAddress" label="收货地址" min-width="240" show-overflow-tooltip /><el-table-column label="操作" width="240"><template #default="s"><el-button v-if="[3, 4].includes(s.row.orderStatus)" link type="primary" @click="viewAttachments(s.row)">查看回传单</el-button><el-button v-if="s.row.orderStatus === 2" link type="primary" @click="openShip(s.row)">登记发货</el-button><el-button v-if="s.row.orderStatus === 3" link type="success" @click="confirm(s.row)">确认完成</el-button></template></el-table-column></el-table><el-dialog v-model="attachmentDialog" :title="`订单 ${attachmentOrder?.orderNo || ''} 的盖章回传单`" width="560px"><el-skeleton v-if="attachmentLoading" :rows="3" animated /><el-empty v-else-if="!attachments.length" description="暂无用户上传的盖章回传单" /><el-table v-else :data="attachments" size="small"><el-table-column prop="fileName" label="文件名" min-width="260" /><el-table-column prop="createdAt" label="上传时间" width="170" /><el-table-column label="查看" width="90"><template #default="s"><el-link :href="attachmentUrl(s.row.fileUrl)" target="_blank" type="primary">打开</el-link></template></el-table-column></el-table></el-dialog><el-dialog v-model="shipDialog" title="登记发货" width="520px"><el-descriptions :column="1" border size="small"><el-descriptions-item label="订单号">{{ shipForm.orderNo }}</el-descriptions-item><el-descriptions-item label="收货人">{{ shipForm.receiverName }}</el-descriptions-item><el-descriptions-item label="收货电话">{{ shipForm.receiverPhone }}</el-descriptions-item><el-descriptions-item label="收货地址">{{ shipForm.receiverAddress }}</el-descriptions-item></el-descriptions><el-form label-width="80px" style="margin-top:16px"><el-form-item label="物流公司" required><el-input v-model="shipForm.company" placeholder="请输入物流公司" /></el-form-item><el-form-item label="物流单号" required><el-input v-model="shipForm.trackingNo" placeholder="请输入物流单号" /></el-form-item></el-form><template #footer><el-button @click="shipDialog = false">取消</el-button><el-button type="primary" @click="submitShip">确认发货</el-button></template></el-dialog></section></template>
